# Generated by Django 3.1.4 on 2021-07-20 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TextSnippet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('shareable_text', models.TextField()),
                ('slug', models.SlugField(unique=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
