# Generated by Django 3.1.4 on 2021-07-24 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_remove_textsnippet_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='textsnippet',
            name='secret_key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
